markdown: rdiscount
pygments: true
auto: true
permalink: /blog/:title
domain: intransitione.com
title: intransitione.com
url: http://www.intransitione.com
feed: http://feeds.feedburner.com/Intransitionecom
disqus_shortname: intransitionecom
