markdown: rdiscount
pygments: true
permalink: /blog/:title
domain: intransitione.com
production: true
title: intransitione.com
url: http://www.intransitione.com
paginate: 3
feed: http://feeds.feedburner.com/Intransitionecom
disqus_shortname: intransitionecom
