markdown: rdiscount
pygments: true
auto: true
permalink: /blog/:title
domain: intransitione.com
title: intransitione.com
url: http://www.intransitione.com
feed: http://feeds.feedburner.com/Intransitionecom

#
# # google_analytics:
# #   account: UA-XXXXX-X
#
# # github:
# #   username: ghusername
#
# # disqus:
# #   id: disqusid
