markdown: rdiscount
pygments: true
auto: true
permalink: /blog/:title
domain: intransitione.com

feedburner:
    id: Intransitionecom
#
# # google_analytics:
# #   account: UA-XXXXX-X
#
# # github:
# #   username: ghusername
#
# # disqus:
# #   id: disqusid
